/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo {
    private var real: Int = 6
    private var imaginario : Int = 7

    fun recibirvalores(real: Int, imaginario: Int){
        this.real = real
        this.imaginario= imaginario
    } 
    fun darnumeros() {
        println("Numero complejo: ${real}+${imaginario}i")
    }
    fun enstring(): String{
        return "(${real} + ${imaginario}i)"
    }
}

fun main() {
    val complejo: Complejo
    complejo=Complejo()
    complejo.darnumeros()
    complejo.recibirvalores(4,5)
    println("\nCon nuevos valores...")
    complejo.darnumeros()
     println("\nReturn en string...")
    println(complejo.enstring())
}

 //_._     _,-'""`-._
 //,-.`._,'(       |\`-/|
 //   `-.-' \ )-`( , o o)
 //         `-    \`_`"'-