/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.math.pow

class Complejo(private var real: Double = 0.0, private var imag: Double = 0.0) {

    // Permite inicializar con Int por comodidad, convirtiendo a Double
    constructor(real: Int, imag: Int) : this(real.toDouble(), imag.toDouble())

    fun mostrar() {
        println(this.toString())
    }

    override fun toString(): String {
        val signo = if (imag >= 0) "+" else "-"
        return "($real $signo ${kotlin.math.abs(imag)}i)"
    }

    fun sumar(valor: Complejo): Complejo {
        return Complejo(real + valor.real, imag + valor.imag)
    }

    fun restar(valor: Complejo): Complejo {
        return Complejo(real - valor.real, imag - valor.imag)
    }

    // --- NUEVAS FUNCIONES ---

    fun multiplicar(valor: Complejo): Complejo {
        // (axc)-(bxd)
        val resul= (real*valor.real) - (imag*valor.imag)
        val resul2 = (real*valor.imag) + (imag*valor.real)
        return Complejo(resul, resul2)
    }

    fun dividir(valor: Complejo): Complejo {
        val resul= (real/valor.real) - (imag/valor.imag)
        val resul2 = (real/valor.imag) + (imag/valor.real) 
        return Complejo(resul, resul2)
    }
}

fun main() {
    var c1 = Complejo(3.0, 4.0)
    var c2 = Complejo(1.0, 2.0)

    println("Numero 1: $c1.mostrar()")
    println("Numero 2: $c2.mostrar()")

    var c3:Complejo= Complejo()

    c3 = c1.sumar(c2)
    println("Suma entre num1 y num2: $c3.mostrar()")

    var c4:Complejo= Complejo()
    c4 = c1.restar(c2)
    println("resta entre num1 y num2: $c4.mostrar()")

    // Multiplicación
    val producto = c1.multiplicar(c2)
    print("Multiplicación entre 1 y 2: ")
    producto.mostrar()

    // División
    val cociente = c1.dividir(c2)
    print("División: ")
    cociente.mostrar()
}

 //_._     _,-'""`-._
 //,-.`._,'(       |\`-/|
 //   `-.-' \ )-`( , o o)
 //         `-    \`_`"'-